### ISSUE TITLE
README missing instructions to install libsdl (or mention of it)

### ISSUE THREAD

**Issue by blazingkin** [czipperz/tesh#18]

**Comment by blazingkin** [comment]
libsdl2-image-dev needed as well

**Comment by blazingkin** [comment]
Aaand libsdl2-ttf-dev

**Comment by czipperz** [comment]
closing via https://github.com/czipperz/tesh/commit/479b8409e3d4435ad44858e074f9c5aed37a57ed
copy/pasted from Mag :)
