### ISSUE TITLE
`ls | grep a` never terminates.

### ISSUE THREAD

**Issue by blazingkin** [czipperz/tesh#3]

**Comment by czipperz** [comment]
I'm assuming built-in `ls`

**Comment by czipperz** [comment]
Does this repo with other built-ins?

**Comment by czipperz** [comment]
I think this is happening because we don't close fds until the Running_Pipeline has ended. Instead we should reference count files. Decrement count at end of Running_Program (Running_Process?)

**Comment by czipperz** [comment]
Pretty sure this is fixed
