### ISSUE TITLE
Feature: Add a way to pipe the output of a command into another command

### ISSUE THREAD

**Issue by blazingkin** [czipperz/tesh#8]
To fill the use case of shell's $<()

**Comment by czipperz** [comment]
$() is implemented already: `a $(b)` becomes `b | __tesh_set_var temp; a $temp`
If <() is synchronous then we could just transform `a <(b)` to `temp=$(mktemp); b > $temp; a $temp`.  Async would have to do something like `temp=$(mktemp); b > $temp &; temp2=$!; a $temp; temp3=$?; wait $temp2; return $temp3`

**Comment by czipperz** [comment]
Implemented synchronous `<()` in 3068960
